version: '3.4'
services:

  env.test:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8881:8881"
      - "8443:443"
    volumes:
        - ./:/var/www
        - ./docker/config/nginx/conf.d/envtest.conf:/etc/nginx/conf.d/default.conf:ro
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php-fpm/Dockerfile
      target: develop
    image: php-fpm:latest
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  mysql:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/mysql/Dockerfile
      target: develop
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - $PWD/docker/volumes/mysql:/var/lib/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=cake_app
      - MYSQL_USER=cake_usr
      - MYSQL_PASSWORD=cake_pw

  mailtrap:
    image: eaudeweb/mailtrap:latest
    container_name: mailtrap
    environment:
      - MT_USER=mailtrap
      - MT_PASSWD=mailtrap
    ports:
      - "2225:25"
      - "8882:80"
